name: "my first example"
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: list and read file
            run: |
              echo "my first GitHub Action Job"
              ls -l
              cat README.md
          - name: install cowsay 
            run: sudo apt-get install cowsay

          - name: Generate ASCII Artwork
            run: cowsay -f dragon "run for cover, I am a DRAGON....RAWR" >> dragon.txt

          - name: READ Artifact
            run: |
              cat dragon.txt
              ls -l
