name: "my first example"
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: welcome message
            run: |
              echo "my first GitHub Action Job"
              ls -l
              cat README.md