name: "Generate ASCII artwork"
on: push

jobs:
    build_01_job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: list and read file
            run: |
              sudo apt-get install cowsay
              cowsay -f dragon "run for cover, I am a DRAGON....RAWR" >> dragon.txt 
          
          - name: upload artifacts
            uses: actions/upload-artifact@v7
            with:
              name: dragon_file
              path: dragon.txt 
    test_02_job:
      needs: build_01_job
      runs-on: ubuntu-latest
      steps:
        - name: download artifacts
          uses: actions/download-artifact@v7
          with:
            name: dragon_file

        - name: test the file 
          run: grep dragon dragon.txt

    deploy_03_job:
      needs: test_02_job
      runs-on: ubuntu-latest
      steps:
        - name: download artifacts
          uses: actions/download-artifact@v7
          with:
            name: dragon_file
        
        - name: deploy file
          run: cat dragon.txt

        - name: marking
          run: echo deployment completed...
             


        

          
