name: "Variable and Secret Demo"
on: 
    push

env:
    CONTAINER_REGISTER: "docker.io"
    USERNAME: "virendray"
    IMAGENAME: "github-actions-nginx"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: socker build 
              run: echo docker build -t ${{env.CONTAINER_REGISTER}}/${{env.USERNAME}}/${{env.IMAGENAME}}:latest

            - name: docker login
              env: 
                PASSWORD: "bsvjhfvjdhk"
              run:  echo docker login --username=${{env.USERNAME}} --password=${{env.PASSWORD}}

            - name: docker publish
              run: echo docker push ${{env.CONTAINER_REGISTER}}/${{env.USERNAME}}/${{env.IMAGENAME}}:latest
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: docker run
              run: echo docker run -d -p 8000:80 ${{env.CONTAINER_REGISTER}}/${{env.USERNAME}}/${{env.IMAGENAME}}:latest


 