name: "Variable and Secret Demo"
on: 
    push

env:
    CONTAINER_REGISTER: "docker.io"
    USERNAME: "virendray"
    PASSWORD: "Arush@Viru@12"
    IMAGENAME: "github-actions-nginx"
    
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: socker build 
              run: docker build -t ${{env.CONTAINER_REGISTER}}/${{env.USERNAME}}/${{env.IMAGENAME}}:latest

            - name: docker login
              run: docker login --username=${{env.USERNAME}} --password=${{env.PASSWORD}}

            - name: docker publish
              run: docker push ${{env.CONTAINER_REGISTER}}/${{env.USERNAME}}/${{env.IMAGENAME}}:latest
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: docker run
              run: docker run -d -p 8000:80 ${{env.CONTAINER_REGISTER}}/${{env.USERNAME}}/${{env.IMAGENAME}}:latest


 