name: build code
on:
  push:
    branches:
      - smoketest
  pull_request:
  
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: install ansile-lint
        run: |
           python -m pip install --upgrade pip
           pip install ansible ansible-lint yamllint

      - name: Run yamllint
        run: |
          yamllint . --format github

      - name: Run ansible-lint
        run: |
          ansible-lint .
