name: Demo workflow
on: workflow_dispatch
jobs:
  build-job:
    run-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello World"
      - name: Print Goodby
        run: echo "Completed - bye"
