---
name: "build code"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Get code"
        uses: actions/checkout@v3

      - name: install ansile-lint
        run: |
           python -m pip install --upgrade pip
           pip install ansible-lint yamllint

      - name: Run ansible-lint
        run: |
          ansible-lint .

      - name: Run yamllint
        run: |
          yamllint . --format github
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: "Get code"
        uses: actions/checkout@v3

      - name: install ansile
        run: |
           python -m pip install --upgrade pip
           pip install ansible

      - name: run playbook
        run: |
          ansible-playbook -i ./inventory/hosts playbooks/01_test.yml

      - name: upload arctifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-logs
          path: ANSIBLE.LOG
...
