name: "Generate ASCII artwork"
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: list repo files
            run: ls -l

          - name: list and read file
            run: ./ascii-script.sh 

          
